services:
  uncom_ros:
    image: uncom_ros:latest
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - ./src/arm_commander:/root/catkin_ws/src/arm_commander:rw
      - ./src/pal_interaction_msgs:/root/catkin_ws/src/pal_interaction_msgs:rw
      - ./src/tiago_robot:/root/catkin_ws/src/tiago_robot:rw
      - ./src/uncom:/root/catkin_ws/src/uncom:rw

    environment: 
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://tiago-218c:11311}
      - ROS_IP=${ROS_IP:-10.68.0.128}
    command: >
      bash -c "source /opt/ros/noetic/setup.bash &&
               cd /root/catkin_ws &&
               catkin build &&
               source /root/catkin_ws/devel/setup.bash &&
               roslaunch uncom uncom.launch"

    stdin_open: true
    tty: true
